name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/amd64,linux/arm64

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Extract Image Name from Repository
        id: repo_name
        run: echo "IMAGE_NAME_PREFIX=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV

      - name: Build and Tag Docker Images
        run: |
          IMAGE="$IMAGE_NAME_PREFIX"
          docker buildx build \
            --load \
            --platform linux/amd64 \
            --tag $IMAGE:latest \
            --tag $IMAGE:${{ github.sha }} \
            --file Dockerfile .

      - name: Push Docker Images to GHCR
        if: github.event_name == 'push'  # Avoid pushing images on PRs
        run: |
          IMAGE="$IMAGE_NAME_PREFIX"
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
